version: '3.8'
services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresps
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - personaltaskmanagement_pgdata:/var/lib/postgresql/data

volumes:
  personaltaskmanagement_pgdata:
