version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: personaltaskmanagement
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresps
      POSTGRES_DB: personaltaskmanagement
    ports:
      - "5433:5432"  # Changed to avoid conflicts with local PostgreSQL
    volumes:
      - personaltaskmanagement_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  personaltaskmanagement_data:
    driver: local